### ISSUE TITLE
Could you please tell me where can I found a Chat widget(RestoBot)

### ISSUE THREAD

**Issue by muralikrishnapeddisetti** [JiteshGaikwad/Restaurant-Search-Bot#1]
Hi Jitesh,

Could you please tell me where can I found a Chat widget(RestoBot).

I have used your Zomato chatbot and the bot has displayed all restaurants as a carousel. In carousel, I was not able to do any operation. Please tell how to solve this problem.

![Capture](https://user-images.githubusercontent.com/24698105/78554212-606cf600-7828-11ea-9ed9-7ea322de2278.PNG)

**Comment by JiteshGaikwad** [comment]
hey @muralikrishnapeddisetti , I haven't released that part of the code which handles the click event of the card carousel, I have made it private
